name: Hello World Automatique

on:
  push:
    branches: [ main ]

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le message
        run: echo "🎉 Mon premier workflow GitHub Actions !"
      
      - name: Afficher la date
        run: echo "🚀 Exécuté le $(date)"
